### ISSUE TITLE
BUG_S1_HU02_display_date

### ISSUE THREAD

**Issue by crisman9211** [garayurbina-uniandes/app-moviles-vinilos#51]
## Descripción error
* Formato de fecha incorrecto
* Solo se  debería mostrar año mes y día de lanzamiento 

## Evidencia 
![image](https://user-images.githubusercontent.com/77636252/140682114-0829391d-20d7-4b57-a59c-3c37ab1688b0.png)

**Comment by diazclaudia1** [comment]
Resuelto
